{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "9: All Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(requestHTTP_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "8: CreationFailures",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pizza_perMinute{method=\"creationFailures\"}",
     "legendFormat": "Creation Failures"
    }
   ]
  },
  {
   "title": "8: Revenue Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizza_perMinute{method=\"revenue\"}[$__rate_interval])",
     "legendFormat": "Bicoin Revenue"
    }
   ]
  },
  {
   "title": "8: CPU and Memory Usage (Respectively)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percentage{method=\"usage\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_percentage{method=\"usage\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "8: Pizza's Sold Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pizza_perMinute{method=\"sold\"}[$__rate_interval])",
     "legendFormat": "Pizza's Sold"
    }
   ]
  },
  {
   "title": "8: Users Logged In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "users_count{method=\"active\"}",
     "legendFormat": "Active User Count"
    }
   ]
  },
  {
   "title": "8: Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "latency_ms{method=\"order\"}",
     "legendFormat": "Latency in Milliseconds"
    }
   ]
  },
  {
   "title": "8: Auth Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(auth_failed{method=\"attempts\"}[$__rate_interval])",
     "legendFormat": "Failed Requests"
    },
    {
     "expr": "rate(auth_successful{method=\"attempts\"}[$__rate_interval])",
     "legendFormat": "Successful Requests"
    }
   ]
  },
  {
   "title": "8: Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "http_latency{method=\"request\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Grafana Metrics Assignment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "request_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana Logging Assignment",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  }
 ]
}